version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    container_name: backend
    working_dir: /usr/src/backend
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/usr/src/backend
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  api:
    container_name: api
    working_dir: /usr/src/api
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./api/:/usr/src/api
    command: "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

