version: "3.9"
   
services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    container_name: api
    working_dir: /usr/src/backend
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/usr/src/backend
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
